# Generated by Django 5.0.4 on 2024-04-07 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('tipoIdentificacion', models.CharField(max_length=3)),
                ('identificacion', models.CharField(max_length=30, unique=True)),
                ('fechaIngreso', models.DateField()),
                ('cargo', models.CharField(max_length=150)),
                ('departamento', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=10)),
                ('indicativo', models.CharField(max_length=100)),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleado')),
            ],
        ),
    ]
