# Generated by Django 5.0.4 on 2024-04-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipoIdentificacion',
            field=models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía')], max_length=3),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='tipo',
            field=models.CharField(choices=[('Cel', 'Celular'), ('Tel', 'Telefono')], max_length=4),
        ),
    ]
