# Generated by Django 5.0.4 on 2024-04-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_empleado_tipoidentificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='tipo',
            field=models.CharField(choices=[('Cell', 'Celular'), ('Tel', 'Telefono')], max_length=4),
        ),
    ]
